VALKMODEL_PRESETS = {
    "130m": {
        "hidden_size": 768,
        "num_hidden_layers": 12,
        "num_heads": 6,
        "head_dim": 96,
        "num_v_heads": 6,
        "max_position_embeddings": 272_000,
    },
    "260m": {
        "hidden_size": 1024,
        "num_hidden_layers": 18,
        "num_heads": 8,
        "head_dim": 96,
        "num_v_heads": 8,
        "max_position_embeddings": 272_000,
    },
    "520m": {
        "hidden_size": 1536,
        "num_hidden_layers": 24,
        "num_heads": 12,
        "head_dim": 96,
        "num_v_heads": 12,
        "max_position_embeddings": 512_000,
    },
    "780m": {
        "hidden_size": 1792,
        "num_hidden_layers": 28,
        "num_heads": 14,
        "head_dim": 96,
        "num_v_heads": 14,
        "max_position_embeddings": 512_000,
    },
    "1.2b": {
        "hidden_size": 2048,
        "num_hidden_layers": 32,
        "num_heads": 16,
        "head_dim": 96,
        "num_v_heads": 16,
        "max_position_embeddings": 768_000,
    },
    "2.8b": {
        "hidden_size": 3072,
        "num_hidden_layers": 40,
        "num_heads": 24,
        "head_dim": 96,
        "num_v_heads": 24,
        "max_position_embeddings": 1_000_000,
    },
    "5b": {
        "hidden_size": 4096,
        "num_hidden_layers": 48,
        "num_heads": 32,
        "head_dim": 96,
        "num_v_heads": 32,
        "max_position_embeddings": 1_000_000,
    },
    "8b": {
        "hidden_size": 5120,
        "num_hidden_layers": 56,
        "num_heads": 40,
        "head_dim": 96,
        "num_v_heads": 40,
        "max_position_embeddings": 1_000_000,
    },
}
